### ISSUE TITLE
Deploying content package throws NullPointerException if package already exists

### ISSUE THREAD

**Issue by ashlyjose** [adamcin/crx-content-package-deployer#1]
Hi,
This is happening in AEM 6. While trying to deploy a package in AEM 6 and if the package already exists, NullPointerException is thrown from the code and the deployment fails.
Works fine if the package does not already exists in AEM. Below is the error:

FATAL: Failed to deploy package: null
java.lang.NullPointerException
    at net.adamcin.granite.client.packman.AbstractPackageManagerClient.existsOnServer(AbstractPackageManagerClient.java:823)
    at org.jenkinsci.plugins.graniteclient.DeployPackageCallable$Execution.doExecute(DeployPackageCallable.java:71)
    at org.jenkinsci.plugins.graniteclient.DeployPackageCallable$Execution.doExecute(DeployPackageCallable.java:61)
    at org.jenkinsci.plugins.graniteclient.GraniteClientExecutor.execute(GraniteClientExecutor.java:87)
    at org.jenkinsci.plugins.graniteclient.DeployPackageCallable.invoke(DeployPackageCallable.java:123)
    at org.jenkinsci.plugins.graniteclient.DeployPackageCallable.invoke(DeployPackageCallable.java:42)
    at hudson.FilePath.act(FilePath.java:980)
    at hudson.FilePath.act(FilePath.java:958)
    at org.jenkinsci.plugins.graniteclient.DeployPackagesBuilder.perform(DeployPackagesBuilder.java:273)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:770)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:533)
    at hudson.model.Run.execute(Run.java:1745)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:89)
    at hudson.model.Executor.run(Executor.java:240)
Build step 'Deploy Content Packages to CRX' changed build result to FAILURE
Build step 'Deploy Content Packages to CRX' marked build as failure
Finished: FAILURE

Thanks,

**Comment by ashlyjose** [comment]
To add to the above, I'm using version 1.3.2 installed from 
https://wiki.jenkins-ci.org/display/JENKINS/CRX+Content+Package+Deployer+Plugin
