### ISSUE TITLE
java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper

### ISSUE THREAD

**Issue by wykapedia** [adamcin/crx-content-package-deployer#3]
This happens when using Jenkins ver. 1.607.

Related Error messages:

ERROR: Failed to list package files: remote file operation failed

FATAL: No package found matching filter *.zip
java.io.IOException: No package found matching filter *.zip
    at org.jenkinsci.plugins.graniteclient.DeployPackagesBuilder.selectPackages(DeployPackagesBuilder.java:338)
    at org.jenkinsci.plugins.graniteclient.DeployPackagesBuilder.perform(DeployPackagesBuilder.java:259)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:761)
    at hudson.model.Build$BuildExecution.build(Build.java:203)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:536)
    at hudson.model.Run.execute(Run.java:1741)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:374)

**Comment by goffinf** [comment]
We are also seeing exactly this behaviour using the plugin on Jenkins v1.580.1 and it is a significant issue for us. Not sure if the workaround to execute the job on MASTER will work, but ideally we don't want to do that. We can probably use the Package Manager API directly too, but again, would prefer not to.

Any ETA on when there might be a fix ??

**Comment by SebastianTroy** [comment]
Also having the same issue, anyone resolved this yet?

**Comment by steeleforge** [comment]
You may be using the wrong package filter format. Try to wildcard the group and version. _:<crx package artifactId>:_
See DefaultPackIdFilter#include

**Comment by SebastianTroy** [comment]
Hi David,
your email was apparently in response to something, but without context I cannot work out exactly what! I imagine it is related to this issue https://issues.jenkins-ci.org/browse/JENKINS-29938 but your suggestion would appear to be more relevant to someone who is working on the Doxygen plugin, as opposed to someone who simply has an issue with it.
Thanks for the tip, if I have the time I'll look 
----Original message----
From : notifications@github.com
Date : 28/10/2015 - 00:18 (GMTST)
To : crx-content-package-deployer@noreply.github.com
Cc : sebastiantroy@btinternet.com
Subject : Re: [crx-content-package-deployer] java.io.IOException: Unable to serialize hudson.FilePath$FileCallableWrapper (#3)
You may be using the wrong package filter format. Try to wildcard the group and version. ::
See DefaultPackIdFilter#include
